//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace optimizerDuck.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("optimizerDuck.Resources.Languages.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Button_Clear {
            get {
                return ResourceManager.GetString("Button.Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy GUID.
        /// </summary>
        public static string Button_CopyGuid {
            get {
                return ResourceManager.GetString("Button.CopyGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Button_Ok {
            get {
                return ResourceManager.GetString("Button.Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Button_Open {
            get {
                return ResourceManager.GetString("Button.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Button_Retry {
            get {
                return ResourceManager.GetString("Button.Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied on {0} days ago.
        /// </summary>
        public static string Common_AppliedDaysAgo {
            get {
                return ResourceManager.GetString("Common.AppliedDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied on {0} hours ago.
        /// </summary>
        public static string Common_AppliedHoursAgo {
            get {
                return ResourceManager.GetString("Common.AppliedHoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just applied.
        /// </summary>
        public static string Common_AppliedJustNow {
            get {
                return ResourceManager.GetString("Common.AppliedJustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied on {0} minutes ago.
        /// </summary>
        public static string Common_AppliedMinutesAgo {
            get {
                return ResourceManager.GetString("Common.AppliedMinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied on {0} months ago.
        /// </summary>
        public static string Common_AppliedMonthsAgo {
            get {
                return ResourceManager.GetString("Common.AppliedMonthsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied on {0} seconds ago.
        /// </summary>
        public static string Common_AppliedSecondsAgo {
            get {
                return ResourceManager.GetString("Common.AppliedSecondsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied on {0} years ago.
        /// </summary>
        public static string Common_AppliedYearsAgo {
            get {
                return ResourceManager.GetString("Common.AppliedYearsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Common_Unknown {
            get {
                return ResourceManager.GetString("Common.Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join our Discord community to... get support or play games with me.
        /// </summary>
        public static string Dashboard_Actions_Discord_Description {
            get {
                return ResourceManager.GetString("Dashboard.Actions.Discord.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord Community.
        /// </summary>
        public static string Dashboard_Actions_Discord_Title {
            get {
                return ResourceManager.GetString("Dashboard.Actions.Discord.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore, review, and contribute to my project through GitHub.
        /// </summary>
        public static string Dashboard_Actions_GitHub_Description {
            get {
                return ResourceManager.GetString("Dashboard.Actions.GitHub.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub Repository.
        /// </summary>
        public static string Dashboard_Actions_GitHub_Title {
            get {
                return ResourceManager.GetString("Dashboard.Actions.GitHub.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support me and keep this project growing!.
        /// </summary>
        public static string Dashboard_Actions_SupportMe_Description {
            get {
                return ResourceManager.GetString("Dashboard.Actions.SupportMe.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Me.
        /// </summary>
        public static string Dashboard_Actions_SupportMe_Title {
            get {
                return ResourceManager.GetString("Dashboard.Actions.SupportMe.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Dashboard_Header_Menu_Header_Options {
            get {
                return ResourceManager.GetString("Dashboard.Header.Menu.Header.Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string Dashboard_Header_Menu_Header_Run {
            get {
                return ResourceManager.GetString("Dashboard.Header.Menu.Header.Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Dashboard_Header_Menu_Refresh {
            get {
                return ResourceManager.GetString("Dashboard.Header.Menu.Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Panel.
        /// </summary>
        public static string Dashboard_Header_Menu_RunControlPanel {
            get {
                return ResourceManager.GetString("Dashboard.Header.Menu.RunControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Dashboard_Header_Menu_RunSettings {
            get {
                return ResourceManager.GetString("Dashboard.Header.Menu.RunSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Manager.
        /// </summary>
        public static string Dashboard_Header_Menu_RunTaskManager {
            get {
                return ResourceManager.GetString("Dashboard.Header.Menu.RunTaskManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard_Header_Title {
            get {
                return ResourceManager.GetString("Dashboard.Header.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Cores.
        /// </summary>
        public static string Dashboard_SystemInfo_Cpu_Cores {
            get {
                return ResourceManager.GetString("Dashboard.SystemInfo.Cpu.Cores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Threads.
        /// </summary>
        public static string Dashboard_SystemInfo_Cpu_Threads {
            get {
                return ResourceManager.GetString("Dashboard.SystemInfo.Cpu.Threads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + {0} more GPU.
        /// </summary>
        public static string Dashboard_SystemInfo_Gpu_More {
            get {
                return ResourceManager.GetString("Dashboard.SystemInfo.Gpu.More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching System Information....
        /// </summary>
        public static string Dashboard_SystemInfo_Loading {
            get {
                return ResourceManager.GetString("Dashboard.SystemInfo.Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} GB Available.
        /// </summary>
        public static string Dashboard_SystemInfo_Ram_Available {
            get {
                return ResourceManager.GetString("Dashboard.SystemInfo.Ram.Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Module(s).
        /// </summary>
        public static string Dashboard_SystemInfo_Ram_Modules {
            get {
                return ResourceManager.GetString("Dashboard.SystemInfo.Ram.Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} GB Used.
        /// </summary>
        public static string Dashboard_SystemInfo_Ram_Used {
            get {
                return ResourceManager.GetString("Dashboard.SystemInfo.Ram.Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} GB used of {1} GB ({2} GB free).
        /// </summary>
        public static string Dashboard_SystemInfo_Storage_DiskInfo {
            get {
                return ResourceManager.GetString("Dashboard.SystemInfo.Storage.DiskInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        public static string Dashboard_SystemInfo_Storage_Header {
            get {
                return ResourceManager.GetString("Dashboard.SystemInfo.Storage.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYSTEM.
        /// </summary>
        public static string Dashboard_SystemInfo_Storage_System {
            get {
                return ResourceManager.GetString("Dashboard.SystemInfo.Storage.System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to proceed?.
        /// </summary>
        public static string Dialog_AreYouSure_Title {
            get {
                return ResourceManager.GetString("Dialog.AreYouSure.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Optimization_Apply_Completed {
            get {
                return ResourceManager.GetString("Optimization.Apply.Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to apply {0}..
        /// </summary>
        public static string Optimization_Apply_Error_Failed {
            get {
                return ResourceManager.GetString("Optimization.Apply.Error.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied {0} with {1} failed step(s)..
        /// </summary>
        public static string Optimization_Apply_Error_FailedWithSteps {
            get {
                return ResourceManager.GetString("Optimization.Apply.Error.FailedWithSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying changes....
        /// </summary>
        public static string Optimization_Apply_Processing {
            get {
                return ResourceManager.GetString("Optimization.Apply.Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t apply optimization..
        /// </summary>
        public static string Optimization_Apply_Snackbar_Error_Title {
            get {
                return ResourceManager.GetString("Optimization.Apply.Snackbar.Error.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully applied {0}..
        /// </summary>
        public static string Optimization_Apply_Success {
            get {
                return ResourceManager.GetString("Optimization.Apply.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrying failed steps....
        /// </summary>
        public static string Optimization_Retry_Processing {
            get {
                return ResourceManager.GetString("Optimization.Retry.Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrying {0} step ({1}/{2} steps).
        /// </summary>
        public static string Optimization_RetryStep_Processing {
            get {
                return ResourceManager.GetString("Optimization.RetryStep.Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to revert {0}..
        /// </summary>
        public static string Optimization_Revert_Error_Failed {
            get {
                return ResourceManager.GetString("Optimization.Revert.Error.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverted {0} with {1} failed step(s)..
        /// </summary>
        public static string Optimization_Revert_Error_FailedWithSteps {
            get {
                return ResourceManager.GetString("Optimization.Revert.Error.FailedWithSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing revert step: {0}/{1} ({2}).
        /// </summary>
        public static string Optimization_Revert_ExecutingStep {
            get {
                return ResourceManager.GetString("Optimization.Revert.ExecutingStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverting....
        /// </summary>
        public static string Optimization_Revert_Reverting {
            get {
                return ResourceManager.GetString("Optimization.Revert.Reverting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t revert optimization.
        /// </summary>
        public static string Optimization_Revert_Snackbar_Error_Title {
            get {
                return ResourceManager.GetString("Optimization.Revert.Snackbar.Error.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully reverted {0}!.
        /// </summary>
        public static string Optimization_Revert_Success {
            get {
                return ResourceManager.GetString("Optimization.Revert.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred: {0}.
        /// </summary>
        public static string Optimization_Toggle_Snackbar_Error_Message {
            get {
                return ResourceManager.GetString("Optimization.Toggle.Snackbar.Error.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t toggle optimization.
        /// </summary>
        public static string Optimization_Toggle_Snackbar_Error_Title {
            get {
                return ResourceManager.GetString("Optimization.Toggle.Snackbar.Error.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed description.
        /// </summary>
        public static string OptimizationDetailsDialog_DetailedDescription {
            get {
                return ResourceManager.GetString("OptimizationDetailsDialog.DetailedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string OptimizationDetailsDialog_Other {
            get {
                return ResourceManager.GetString("OptimizationDetailsDialog.Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the folder and select the rollback data file for this optimization..
        /// </summary>
        public static string OptimizationDetailsDialog_Other_OpenRevertFile_Description {
            get {
                return ResourceManager.GetString("OptimizationDetailsDialog.Other.OpenRevertFile.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert file.
        /// </summary>
        public static string OptimizationDetailsDialog_Other_OpenRevertFile_Title {
            get {
                return ResourceManager.GetString("OptimizationDetailsDialog.Other.OpenRevertFile.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk.
        /// </summary>
        public static string OptimizationDetailsDialog_Risk {
            get {
                return ResourceManager.GetString("OptimizationDetailsDialog.Risk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string OptimizationDetailsDialog_Tags {
            get {
                return ResourceManager.GetString("OptimizationDetailsDialog.Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some steps didn&apos;t complete successfully. You can retry only the failed steps..
        /// </summary>
        public static string OptimizationResultDialog_Description {
            get {
                return ResourceManager.GetString("OptimizationResultDialog.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Failed steps.
        /// </summary>
        public static string OptimizationResultDialog_Header {
            get {
                return ResourceManager.GetString("OptimizationResultDialog.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloatware &amp; Services.
        /// </summary>
        public static string Optimizer_BloatwareAndServices {
            get {
                return ResourceManager.GetString("Optimizer.BloatwareAndServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize Service Startup.
        /// </summary>
        public static string Optimizer_BloatwareAndServices_ConfigureServices_Name {
            get {
                return ResourceManager.GetString("Optimizer.BloatwareAndServices.ConfigureServices.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting startup type for {0} to {1}....
        /// </summary>
        public static string Optimizer_BloatwareAndServices_ConfigureServices_Progress_ChangeServiceStartupType {
            get {
                return ResourceManager.GetString(("Optimizer.BloatwareAndServices.ConfigureServices.Progress.ChangeServiceStartupTyp" +
                        "e"), resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switches non-critical system services to manual start, reducing background usage without breaking functionality. Required services will start automatically when needed..
        /// </summary>
        public static string Optimizer_BloatwareAndServices_ConfigureServices_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.BloatwareAndServices.ConfigureServices.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Preinstalled Apps.
        /// </summary>
        public static string Optimizer_BloatwareAndServices_DisablePreinstalledApps_Name {
            get {
                return ResourceManager.GetString("Optimizer.BloatwareAndServices.DisablePreinstalledApps.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocks Windows from automatically installing OEM/bundled apps and suggested apps, helping keep the system cleaner from bloatware (especially after a fresh install or reset)..
        /// </summary>
        public static string Optimizer_BloatwareAndServices_DisablePreinstalledApps_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.BloatwareAndServices.DisablePreinstalledApps.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU.
        /// </summary>
        public static string Optimizer_Gpu {
            get {
                return ResourceManager.GetString("Optimizer.Gpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable AMD ASPM.
        /// </summary>
        public static string Optimizer_Gpu_AmdDisableAspm_Name {
            get {
                return ResourceManager.GetString("Optimizer.Gpu.AmdDisableAspm.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables AMD Active State Power Management to reduce latency and improve responsiveness. May increase PCIe power draw..
        /// </summary>
        public static string Optimizer_Gpu_AmdDisableAspm_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.Gpu.AmdDisableAspm.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable AMD Power Gating.
        /// </summary>
        public static string Optimizer_Gpu_AmdDisablePowerGating_Name {
            get {
                return ResourceManager.GetString("Optimizer.Gpu.AmdDisablePowerGating.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables AMD power gating features to maintain consistent GPU performance under load. May increase power draw and temperatures..
        /// </summary>
        public static string Optimizer_Gpu_AmdDisablePowerGating_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.Gpu.AmdDisablePowerGating.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable AMD ULPS.
        /// </summary>
        public static string Optimizer_Gpu_AmdDisableUlps_Name {
            get {
                return ResourceManager.GetString("Optimizer.Gpu.AmdDisableUlps.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables AMD Ultra Low Power State to prevent GPU power-down issues and improve wake-up latency..
        /// </summary>
        public static string Optimizer_Gpu_AmdDisableUlps_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.Gpu.AmdDisableUlps.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable AMD Video Clock Gating.
        /// </summary>
        public static string Optimizer_Gpu_AmdDisableVideoClockGating_Name {
            get {
                return ResourceManager.GetString("Optimizer.Gpu.AmdDisableVideoClockGating.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables AMD video engine clock gating to improve video processing performance and stability. May increase power usage..
        /// </summary>
        public static string Optimizer_Gpu_AmdDisableVideoClockGating_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.Gpu.AmdDisableVideoClockGating.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Intel Adaptive V-Sync.
        /// </summary>
        public static string Optimizer_Gpu_IntelDisableAdaptiveVsync_Name {
            get {
                return ResourceManager.GetString("Optimizer.Gpu.IntelDisableAdaptiveVsync.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables Intel adaptive vertical sync to provide more consistent frame timing..
        /// </summary>
        public static string Optimizer_Gpu_IntelDisableAdaptiveVsync_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.Gpu.IntelDisableAdaptiveVsync.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Intel Async Flips.
        /// </summary>
        public static string Optimizer_Gpu_IntelDisableAsyncFlips_Name {
            get {
                return ResourceManager.GetString("Optimizer.Gpu.IntelDisableAsyncFlips.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables Intel asynchronous flip operations to reduce display latency and improve tearing resistance..
        /// </summary>
        public static string Optimizer_Gpu_IntelDisableAsyncFlips_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.Gpu.IntelDisableAsyncFlips.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable NVIDIA Async P-States.
        /// </summary>
        public static string Optimizer_Gpu_NvidiaDisableAsyncPstates_Name {
            get {
                return ResourceManager.GetString("Optimizer.Gpu.NvidiaDisableAsyncPstates.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables NVIDIA asynchronous power state management for more predictable performance. May increase power usage..
        /// </summary>
        public static string Optimizer_Gpu_NvidiaDisableAsyncPstates_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.Gpu.NvidiaDisableAsyncPstates.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable NVIDIA Dynamic P-State.
        /// </summary>
        public static string Optimizer_Gpu_NvidiaDisableDynamicPstate_Name {
            get {
                return ResourceManager.GetString("Optimizer.Gpu.NvidiaDisableDynamicPstate.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables NVIDIA dynamic power state transitions to maintain consistent performance. May increase idle power usage..
        /// </summary>
        public static string Optimizer_Gpu_NvidiaDisableDynamicPstate_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.Gpu.NvidiaDisableDynamicPstate.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string Optimizer_Performance {
            get {
                return ResourceManager.GetString("Optimizer.Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Background App Activity.
        /// </summary>
        public static string Optimizer_Performance_DisableBackgroundApps_Name {
            get {
                return ResourceManager.GetString("Optimizer.Performance.DisableBackgroundApps.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocks supported apps from running in the background, reducing idle RAM/CPU usage and improving responsiveness..
        /// </summary>
        public static string Optimizer_Performance_DisableBackgroundApps_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.Performance.DisableBackgroundApps.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Xbox Game Bar.
        /// </summary>
        public static string Optimizer_Performance_DisableGameBar_Name {
            get {
                return ResourceManager.GetString("Optimizer.Performance.DisableGameBar.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables Game Bar UI overlays and tips to reduce background overhead and interruptions..
        /// </summary>
        public static string Optimizer_Performance_DisableGameBar_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.Performance.DisableGameBar.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Game DVR Recording.
        /// </summary>
        public static string Optimizer_Performance_DisableGameDVR_Name {
            get {
                return ResourceManager.GetString("Optimizer.Performance.DisableGameDVR.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turns off background game capture/recording features to free resources and reduce latency..
        /// </summary>
        public static string Optimizer_Performance_DisableGameDVR_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.Performance.DisableGameDVR.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Mouse Acceleration.
        /// </summary>
        public static string Optimizer_Performance_DisableMouseAcceleration_Name {
            get {
                return ResourceManager.GetString("Optimizer.Performance.DisableMouseAcceleration.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables mouse acceleration for consistent, predictable cursor movement..
        /// </summary>
        public static string Optimizer_Performance_DisableMouseAcceleration_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.Performance.DisableMouseAcceleration.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Game Mode.
        /// </summary>
        public static string Optimizer_Performance_EnableGameMode_Name {
            get {
                return ResourceManager.GetString("Optimizer.Performance.EnableGameMode.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables Game Mode to prioritize gaming performance and limit background activity. (Recommended on Windows 11).
        /// </summary>
        public static string Optimizer_Performance_EnableGameMode_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.Performance.EnableGameMode.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Game Task Priority.
        /// </summary>
        public static string Optimizer_Performance_GameTaskScheduling_Name {
            get {
                return ResourceManager.GetString("Optimizer.Performance.GameTaskScheduling.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusts MMCSS “Games” task settings to prioritize game workloads for more consistent frame pacing..
        /// </summary>
        public static string Optimizer_Performance_GameTaskScheduling_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.Performance.GameTaskScheduling.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize Keyboard Responsiveness.
        /// </summary>
        public static string Optimizer_Performance_KeyboardLatencyOptimization_Name {
            get {
                return ResourceManager.GetString("Optimizer.Performance.KeyboardLatencyOptimization.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunes keyboard delay/repeat rate and related accessibility flags to improve typing responsiveness..
        /// </summary>
        public static string Optimizer_Performance_KeyboardLatencyOptimization_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.Performance.KeyboardLatencyOptimization.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize MMCSS Responsiveness.
        /// </summary>
        public static string Optimizer_Performance_MultimediaResponsiveness_Name {
            get {
                return ResourceManager.GetString("Optimizer.Performance.MultimediaResponsiveness.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduces latency by tuning SystemProfile responsiveness and disabling network throttling for gaming and AV workloads..
        /// </summary>
        public static string Optimizer_Performance_MultimediaResponsiveness_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.Performance.MultimediaResponsiveness.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Foreground Boost.
        /// </summary>
        public static string Optimizer_Performance_ProcessPriority_Name {
            get {
                return ResourceManager.GetString("Optimizer.Performance.ProcessPriority.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunes Windows scheduler foreground boost so active apps feel snappier and input latency is reduced..
        /// </summary>
        public static string Optimizer_Performance_ProcessPriority_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.Performance.ProcessPriority.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid RAM: {0}.
        /// </summary>
        public static string Optimizer_Performance_SvcHostSplit_Error_InvalidRAM {
            get {
                return ResourceManager.GetString("Optimizer.Performance.SvcHostSplit.Error.InvalidRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Service Host Splitting.
        /// </summary>
        public static string Optimizer_Performance_SvcHostSplit_Name {
            get {
                return ResourceManager.GetString("Optimizer.Performance.SvcHostSplit.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusts Service Host split threshold based on installed RAM to improve process isolation and stability..
        /// </summary>
        public static string Optimizer_Performance_SvcHostSplit_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.Performance.SvcHostSplit.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Management.
        /// </summary>
        public static string Optimizer_PowerManagement {
            get {
                return ResourceManager.GetString("Optimizer.PowerManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Hibernate &amp; Fast Startup.
        /// </summary>
        public static string Optimizer_PowerManagement_DisableHibernate_Name {
            get {
                return ResourceManager.GetString("Optimizer.PowerManagement.DisableHibernate.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables Hibernate and Fast Startup to free disk space and avoid using the hiberfile..
        /// </summary>
        public static string Optimizer_PowerManagement_DisableHibernate_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.PowerManagement.DisableHibernate.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Power Throttling.
        /// </summary>
        public static string Optimizer_PowerManagement_DisablePowerSaving_Name {
            get {
                return ResourceManager.GetString("Optimizer.PowerManagement.DisablePowerSaving.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables power throttling and related power-saving behaviors to keep performance stable under load. May increase power use and temperatures..
        /// </summary>
        public static string Optimizer_PowerManagement_DisablePowerSaving_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.PowerManagement.DisablePowerSaving.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable USB Power Saving.
        /// </summary>
        public static string Optimizer_PowerManagement_DisableUSBPowerSaving_Name {
            get {
                return ResourceManager.GetString("Optimizer.PowerManagement.DisableUSBPowerSaving.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevents USB root hubs from entering power-saving mode to reduce latency. May increase power usage on laptops..
        /// </summary>
        public static string Optimizer_PowerManagement_DisableUSBPowerSaving_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.PowerManagement.DisableUSBPowerSaving.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to activate optimizerDuck&apos;s power plan..
        /// </summary>
        public static string Optimizer_PowerManagement_InstallOptimizerDuckPowerPlan_Error_ActivateFailed {
            get {
                return ResourceManager.GetString("Optimizer.PowerManagement.InstallOptimizerDuckPowerPlan.Error.ActivateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to detect the current active power plan..
        /// </summary>
        public static string Optimizer_PowerManagement_InstallOptimizerDuckPowerPlan_Error_DetectActivePlanFailed {
            get {
                return ResourceManager.GetString(("Optimizer.PowerManagement.InstallOptimizerDuckPowerPlan.Error.DetectActivePlanFai" +
                        "led"), resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download optimizerDuck&apos;s power plan..
        /// </summary>
        public static string Optimizer_PowerManagement_InstallOptimizerDuckPowerPlan_Error_DownloadFailed {
            get {
                return ResourceManager.GetString("Optimizer.PowerManagement.InstallOptimizerDuckPowerPlan.Error.DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import optimizerDuck&apos;s power plan..
        /// </summary>
        public static string Optimizer_PowerManagement_InstallOptimizerDuckPowerPlan_Error_ImportFailed {
            get {
                return ResourceManager.GetString("Optimizer.PowerManagement.InstallOptimizerDuckPowerPlan.Error.ImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install optimizerDuck&apos;s Power Plan.
        /// </summary>
        public static string Optimizer_PowerManagement_InstallOptimizerDuckPowerPlan_Name {
            get {
                return ResourceManager.GetString("Optimizer.PowerManagement.InstallOptimizerDuckPowerPlan.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading power plan....
        /// </summary>
        public static string Optimizer_PowerManagement_InstallOptimizerDuckPowerPlan_Progress_Downloading {
            get {
                return ResourceManager.GetString("Optimizer.PowerManagement.InstallOptimizerDuckPowerPlan.Progress.Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing and activating power plan....
        /// </summary>
        public static string Optimizer_PowerManagement_InstallOptimizerDuckPowerPlan_Progress_Importing {
            get {
                return ResourceManager.GetString("Optimizer.PowerManagement.InstallOptimizerDuckPowerPlan.Progress.Importing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads, imports, and activates the optimizerDuck power plan to prioritize maximum performance. May increase power use, heat, and fan noise..
        /// </summary>
        public static string Optimizer_PowerManagement_InstallOptimizerDuckPowerPlan_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.PowerManagement.InstallOptimizerDuckPowerPlan.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security &amp; Privacy.
        /// </summary>
        public static string Optimizer_SecurityAndPrivacy {
            get {
                return ResourceManager.GetString("Optimizer.SecurityAndPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable WMI AutoLogger.
        /// </summary>
        public static string Optimizer_SecurityAndPrivacy_DisableAutoLogger_Name {
            get {
                return ResourceManager.GetString("Optimizer.SecurityAndPrivacy.DisableAutoLogger.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables multiple WMI AutoLogger sessions to reduce background event logging; can make troubleshooting harder..
        /// </summary>
        public static string Optimizer_SecurityAndPrivacy_DisableAutoLogger_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.SecurityAndPrivacy.DisableAutoLogger.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Content Delivery.
        /// </summary>
        public static string Optimizer_SecurityAndPrivacy_DisableContentDeliveryManager_Name {
            get {
                return ResourceManager.GetString("Optimizer.SecurityAndPrivacy.DisableContentDeliveryManager.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stops suggested apps, tips, and Windows content delivery recommendations..
        /// </summary>
        public static string Optimizer_SecurityAndPrivacy_DisableContentDeliveryManager_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.SecurityAndPrivacy.DisableContentDeliveryManager.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Windows Copilot.
        /// </summary>
        public static string Optimizer_SecurityAndPrivacy_DisableCopilot_Name {
            get {
                return ResourceManager.GetString("Optimizer.SecurityAndPrivacy.DisableCopilot.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables Windows Copilot and hides its UI integration in the taskbar and system shell..
        /// </summary>
        public static string Optimizer_SecurityAndPrivacy_DisableCopilot_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.SecurityAndPrivacy.DisableCopilot.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Cortana &amp; Web Search.
        /// </summary>
        public static string Optimizer_SecurityAndPrivacy_DisableCortana_Name {
            get {
                return ResourceManager.GetString("Optimizer.SecurityAndPrivacy.DisableCortana.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes Cortana and web search integration from Windows Search..
        /// </summary>
        public static string Optimizer_SecurityAndPrivacy_DisableCortana_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.SecurityAndPrivacy.DisableCortana.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce Telemetry &amp; Feedback.
        /// </summary>
        public static string Optimizer_SecurityAndPrivacy_DisableTelemetry_Name {
            get {
                return ResourceManager.GetString("Optimizer.SecurityAndPrivacy.DisableTelemetry.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling telemetry services....
        /// </summary>
        public static string Optimizer_SecurityAndPrivacy_DisableTelemetry_Progress_DisableServices {
            get {
                return ResourceManager.GetString("Optimizer.SecurityAndPrivacy.DisableTelemetry.Progress.DisableServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling scheduled telemetry tasks....
        /// </summary>
        public static string Optimizer_SecurityAndPrivacy_DisableTelemetry_Progress_DisableTasks {
            get {
                return ResourceManager.GetString("Optimizer.SecurityAndPrivacy.DisableTelemetry.Progress.DisableTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying policy and registry changes....
        /// </summary>
        public static string Optimizer_SecurityAndPrivacy_DisableTelemetry_Progress_EditRegistry {
            get {
                return ResourceManager.GetString("Optimizer.SecurityAndPrivacy.DisableTelemetry.Progress.EditRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduces Windows diagnostics/telemetry and feedback by applying policies, registry settings, services, and scheduled tasks. May affect error reporting and some compatibility features..
        /// </summary>
        public static string Optimizer_SecurityAndPrivacy_DisableTelemetry_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.SecurityAndPrivacy.DisableTelemetry.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable UAC Prompts.
        /// </summary>
        public static string Optimizer_SecurityAndPrivacy_DisableUAC_Name {
            get {
                return ResourceManager.GetString("Optimizer.SecurityAndPrivacy.DisableUAC.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables UAC (User Account Control) – the mechanism that asks for confirmation when running applications requiring Admin rights. Turning it off may reduce annoyance, but it also weakens important security protections..
        /// </summary>
        public static string Optimizer_SecurityAndPrivacy_DisableUAC_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.SecurityAndPrivacy.DisableUAC.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value reflects the level of intervention and the safety of the optimization process. Please exercise caution and consider carefully before applying any optimization..
        /// </summary>
        public static string Optimizer_UI_Risk_Help {
            get {
                return ResourceManager.GetString("Optimizer.UI.Risk.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate.
        /// </summary>
        public static string Optimizer_UI_Risk_Moderate {
            get {
                return ResourceManager.GetString("Optimizer.UI.Risk.Moderate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risky.
        /// </summary>
        public static string Optimizer_UI_Risk_Risky {
            get {
                return ResourceManager.GetString("Optimizer.UI.Risk.Risky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe.
        /// </summary>
        public static string Optimizer_UI_Risk_Safe {
            get {
                return ResourceManager.GetString("Optimizer.UI.Risk.Safe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMD.
        /// </summary>
        public static string Optimizer_UI_Tags_Amd {
            get {
                return ResourceManager.GetString("Optimizer.UI.Tags.Amd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string Optimizer_UI_Tags_Audio {
            get {
                return ResourceManager.GetString("Optimizer.UI.Tags.Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk.
        /// </summary>
        public static string Optimizer_UI_Tags_Disk {
            get {
                return ResourceManager.GetString("Optimizer.UI.Tags.Disk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string Optimizer_UI_Tags_Display {
            get {
                return ResourceManager.GetString("Optimizer.UI.Tags.Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These tags indicate which parts of the system the optimization will affect..
        /// </summary>
        public static string Optimizer_UI_Tags_Help {
            get {
                return ResourceManager.GetString("Optimizer.UI.Tags.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intel.
        /// </summary>
        public static string Optimizer_UI_Tags_Intel {
            get {
                return ResourceManager.GetString("Optimizer.UI.Tags.Intel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latency.
        /// </summary>
        public static string Optimizer_UI_Tags_Latency {
            get {
                return ResourceManager.GetString("Optimizer.UI.Tags.Latency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string Optimizer_UI_Tags_Network {
            get {
                return ResourceManager.GetString("Optimizer.UI.Tags.Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network connection required.
        /// </summary>
        public static string Optimizer_UI_Tags_NetworkRequired {
            get {
                return ResourceManager.GetString("Optimizer.UI.Tags.NetworkRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NVIDIA.
        /// </summary>
        public static string Optimizer_UI_Tags_Nvidia {
            get {
                return ResourceManager.GetString("Optimizer.UI.Tags.Nvidia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string Optimizer_UI_Tags_Performance {
            get {
                return ResourceManager.GetString("Optimizer.UI.Tags.Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        public static string Optimizer_UI_Tags_Power {
            get {
                return ResourceManager.GetString("Optimizer.UI.Tags.Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Optimizer_UI_Tags_Privacy {
            get {
                return ResourceManager.GetString("Optimizer.UI.Tags.Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ram.
        /// </summary>
        public static string Optimizer_UI_Tags_Ram {
            get {
                return ResourceManager.GetString("Optimizer.UI.Tags.Ram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string Optimizer_UI_Tags_Security {
            get {
                return ResourceManager.GetString("Optimizer.UI.Tags.Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string Optimizer_UI_Tags_System {
            get {
                return ResourceManager.GetString("Optimizer.UI.Tags.System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual.
        /// </summary>
        public static string Optimizer_UI_Tags_Visual {
            get {
                return ResourceManager.GetString("Optimizer.UI.Tags.Visual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Experience.
        /// </summary>
        public static string Optimizer_UserExperience {
            get {
                return ResourceManager.GetString("Optimizer.UserExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Explorer &amp; System Notifications.
        /// </summary>
        public static string Optimizer_UserExperience_DisableExplorerAndSystemNotifications_Name {
            get {
                return ResourceManager.GetString("Optimizer.UserExperience.DisableExplorerAndSystemNotifications.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables various system notifications and sync provider notifications to reduce interruptions..
        /// </summary>
        public static string Optimizer_UserExperience_DisableExplorerAndSystemNotifications_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.UserExperience.DisableExplorerAndSystemNotifications.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Extra Taskbar Buttons.
        /// </summary>
        public static string Optimizer_UserExperience_DisableTaskbarExtraButtons_Name {
            get {
                return ResourceManager.GetString("Optimizer.UserExperience.DisableTaskbarExtraButtons.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hides Widgets, Chat, and Task View buttons from the taskbar for a cleaner interface..
        /// </summary>
        public static string Optimizer_UserExperience_DisableTaskbarExtraButtons_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.UserExperience.DisableTaskbarExtraButtons.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Taskbar News &amp; Interests.
        /// </summary>
        public static string Optimizer_UserExperience_DisableTaskbarNewsAndInterests_Name {
            get {
                return ResourceManager.GetString("Optimizer.UserExperience.DisableTaskbarNewsAndInterests.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the news and interests widget from the taskbar to reduce distractions and resource usage..
        /// </summary>
        public static string Optimizer_UserExperience_DisableTaskbarNewsAndInterests_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.UserExperience.DisableTaskbarNewsAndInterests.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Taskbar Search &amp; Bing.
        /// </summary>
        public static string Optimizer_UserExperience_DisableTaskbarSearchAndBing_Name {
            get {
                return ResourceManager.GetString("Optimizer.UserExperience.DisableTaskbarSearchAndBing.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the search box from taskbar and disables Bing web search integration..
        /// </summary>
        public static string Optimizer_UserExperience_DisableTaskbarSearchAndBing_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.UserExperience.DisableTaskbarSearchAndBing.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Visual Effects.
        /// </summary>
        public static string Optimizer_UserExperience_DisableVisualEffects_Name {
            get {
                return ResourceManager.GetString("Optimizer.UserExperience.DisableVisualEffects.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables taskbar animations, shadows, transparency, and Aero Peek for better performance..
        /// </summary>
        public static string Optimizer_UserExperience_DisableVisualEffects_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.UserExperience.DisableVisualEffects.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Classic Context Menu (for Windows 11).
        /// </summary>
        public static string Optimizer_UserExperience_EnableClassicContextMenu_Name {
            get {
                return ResourceManager.GetString("Optimizer.UserExperience.EnableClassicContextMenu.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restores the classic Windows context menu instead of the modern simplified version..
        /// </summary>
        public static string Optimizer_UserExperience_EnableClassicContextMenu_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.UserExperience.EnableClassicContextMenu.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Dark Mode.
        /// </summary>
        public static string Optimizer_UserExperience_EnableDarkMode_Name {
            get {
                return ResourceManager.GetString("Optimizer.UserExperience.EnableDarkMode.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables dark mode for system apps and interface elements to reduce eye strain..
        /// </summary>
        public static string Optimizer_UserExperience_EnableDarkMode_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.UserExperience.EnableDarkMode.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Taskbar End Task.
        /// </summary>
        public static string Optimizer_UserExperience_EnableTaskbarEndTask_Name {
            get {
                return ResourceManager.GetString("Optimizer.UserExperience.EnableTaskbarEndTask.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds the ability to right-click taskbar applications and select &quot;End task&quot; for quick process termination..
        /// </summary>
        public static string Optimizer_UserExperience_EnableTaskbarEndTask_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.UserExperience.EnableTaskbarEndTask.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Meet Now &amp; People.
        /// </summary>
        public static string Optimizer_UserExperience_RemoveMeetNowAndPeople_Name {
            get {
                return ResourceManager.GetString("Optimizer.UserExperience.RemoveMeetNowAndPeople.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes Meet Now and People icons from the taskbar to reduce clutter..
        /// </summary>
        public static string Optimizer_UserExperience_RemoveMeetNowAndPeople_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.UserExperience.RemoveMeetNowAndPeople.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show File Extensions &amp; Hidden Files.
        /// </summary>
        public static string Optimizer_UserExperience_ShowFileExtensionsAndHiddenFiles_Name {
            get {
                return ResourceManager.GetString("Optimizer.UserExperience.ShowFileExtensionsAndHiddenFiles.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes file extensions visible and shows hidden system files for better file management..
        /// </summary>
        public static string Optimizer_UserExperience_ShowFileExtensionsAndHiddenFiles_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.UserExperience.ShowFileExtensionsAndHiddenFiles.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Seconds in System Clock.
        /// </summary>
        public static string Optimizer_UserExperience_ShowSecondsInSystemClock_Name {
            get {
                return ResourceManager.GetString("Optimizer.UserExperience.ShowSecondsInSystemClock.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds seconds display to the system clock in the taskbar for more precise time tracking..
        /// </summary>
        public static string Optimizer_UserExperience_ShowSecondsInSystemClock_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.UserExperience.ShowSecondsInSystemClock.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed Up Explorer &amp; Menus.
        /// </summary>
        public static string Optimizer_UserExperience_SpeedUpExplorerAndMenus_Name {
            get {
                return ResourceManager.GetString("Optimizer.UserExperience.SpeedUpExplorerAndMenus.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduces Explorer startup delay and menu popup delay for faster interface response..
        /// </summary>
        public static string Optimizer_UserExperience_SpeedUpExplorerAndMenus_ShortDescription {
            get {
                return ResourceManager.GetString("Optimizer.UserExperience.SpeedUpExplorerAndMenus.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please don&apos;t close the app or restart while changes are being applied or reverted..
        /// </summary>
        public static string ProcessingOptimizationDialog_Warning_DontCloseAppOrRestart {
            get {
                return ResourceManager.GetString("ProcessingOptimizationDialog.Warning.DontCloseAppOrRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a restore point....
        /// </summary>
        public static string RestorePoint_Progress_Creating {
            get {
                return ResourceManager.GetString("RestorePoint.Progress.Creating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling System Restore....
        /// </summary>
        public static string RestorePoint_Progress_Enabling {
            get {
                return ResourceManager.GetString("RestorePoint.Progress.Enabling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrying to create the restore point....
        /// </summary>
        public static string RestorePoint_Progress_Retrying {
            get {
                return ResourceManager.GetString("RestorePoint.Progress.Retrying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating or enabling System Restore. Please try creating it manually..
        /// </summary>
        public static string RestorePoint_Snackbar_Error_Message {
            get {
                return ResourceManager.GetString("RestorePoint.Snackbar.Error.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create or enable System Restore..
        /// </summary>
        public static string RestorePoint_Snackbar_Error_Title {
            get {
                return ResourceManager.GetString("RestorePoint.Snackbar.Error.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A restore point has been created with the name: {0}..
        /// </summary>
        public static string RestorePoint_Snackbar_Success_Message {
            get {
                return ResourceManager.GetString("RestorePoint.Snackbar.Success.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore point created successfully.
        /// </summary>
        public static string RestorePoint_Snackbar_Success_Title {
            get {
                return ResourceManager.GetString("RestorePoint.Snackbar.Success.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Restore.
        /// </summary>
        public static string RestorePoint_Title {
            get {
                return ResourceManager.GetString("RestorePoint.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Windows operating system includes a feature called Restore Point, which allows you to revert the system to its previous state before applying any changes or optimizations..
        /// </summary>
        public static string RestorePointDialog_Description {
            get {
                return ResourceManager.GetString("RestorePointDialog.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you proceed, the application will automatically activate System Restore (if it is disabled) and create a new restore point with a name starting with &quot;optimizerDuck...&quot;, helping safeguard the system before any changes..
        /// </summary>
        public static string RestorePointDialog_Help {
            get {
                return ResourceManager.GetString("RestorePointDialog.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert file is empty.
        /// </summary>
        public static string Revert_Error_FileEmpty {
            get {
                return ResourceManager.GetString("Revert.Error.FileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert file not found.
        /// </summary>
        public static string Revert_Error_FileNotFound {
            get {
                return ResourceManager.GetString("Revert.Error.FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid revert data for {0}: {1}.
        /// </summary>
        public static string Revert_Error_InvalidData {
            get {
                return ResourceManager.GetString("Revert.Error.InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid revert data.
        /// </summary>
        public static string Revert_Error_InvalidJson {
            get {
                return ResourceManager.GetString("Revert.Error.InvalidJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JSON format: {0}.
        /// </summary>
        public static string Revert_Error_InvalidJsonFormat {
            get {
                return ResourceManager.GetString("Revert.Error.InvalidJsonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid revert steps: {0}.
        /// </summary>
        public static string Revert_Error_InvalidSteps {
            get {
                return ResourceManager.GetString("Revert.Error.InvalidSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No revert data found for {0}..
        /// </summary>
        public static string Revert_Error_NoDataFound {
            get {
                return ResourceManager.GetString("Revert.Error.NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No revert steps found..
        /// </summary>
        public static string Revert_Error_NoSteps {
            get {
                return ResourceManager.GetString("Revert.Error.NoSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptimizationId mismatch..
        /// </summary>
        public static string Revert_Error_OptimizationIdMismatch {
            get {
                return ResourceManager.GetString("Revert.Error.OptimizationIdMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read revert data: {0}.
        /// </summary>
        public static string Revert_Error_ReadFailed {
            get {
                return ResourceManager.GetString("Revert.Error.ReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to revert {0}: {1}.
        /// </summary>
        public static string Revert_Error_RevertFailed {
            get {
                return ResourceManager.GetString("Revert.Error.RevertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        public static string Service_Common_Error_AccessDenied {
            get {
                return ResourceManager.GetString("Service.Common.Error.AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied (protected hive).
        /// </summary>
        public static string Service_Registry_Error_AccessDeniedProtectedHive {
            get {
                return ResourceManager.GetString("Service.Registry.Error.AccessDeniedProtectedHive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create/open subkey.
        /// </summary>
        public static string Service_Registry_Error_CreateOrOpenSubkeyFailed {
            get {
                return ResourceManager.GetString("Service.Registry.Error.CreateOrOpenSubkeyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized access.
        /// </summary>
        public static string Service_Registry_Error_UnauthorizedAccess {
            get {
                return ResourceManager.GetString("Service.Registry.Error.UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangeStartMode failed (code: {0}).
        /// </summary>
        public static string Service_Service_Error_ChangeStartModeFailedWithCode {
            get {
                return ResourceManager.GetString("Service.Service.Error.ChangeStartModeFailedWithCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service not found.
        /// </summary>
        public static string Service_Service_Error_NotFound {
            get {
                return ResourceManager.GetString("Service.Service.Error.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update registry for startup type.
        /// </summary>
        public static string Service_Service_Error_UpdateRegistryForStartupTypeFailed {
            get {
                return ResourceManager.GetString("Service.Service.Error.UpdateRegistryForStartupTypeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit code {0}.
        /// </summary>
        public static string Service_Shell_Error_ExitCode {
            get {
                return ResourceManager.GetString("Service.Shell.Error.ExitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed out.
        /// </summary>
        public static string Service_Shell_Error_TimedOut {
            get {
                return ResourceManager.GetString("Service.Shell.Error.TimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to optimizerDuck is made possible by the following open-source software and resources..
        /// </summary>
        public static string Settings_About_Acknowledgements_Description {
            get {
                return ResourceManager.GetString("Settings.About.Acknowledgements.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledgments.
        /// </summary>
        public static string Settings_About_Acknowledgements_Title {
            get {
                return ResourceManager.GetString("Settings.About.Acknowledgements.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your trust and support &lt;3! Current version: {0}.
        /// </summary>
        public static string Settings_About_Duck_Description {
            get {
                return ResourceManager.GetString("Settings.About.Duck.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Settings_About_Header {
            get {
                return ResourceManager.GetString("Settings.About.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string Settings_About_LearnMore {
            get {
                return ResourceManager.GetString("Settings.About.LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledgments.
        /// </summary>
        public static string Settings_About_LearnMore_Acknowledgements {
            get {
                return ResourceManager.GetString("Settings.About.LearnMore.Acknowledgements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord community.
        /// </summary>
        public static string Settings_About_LearnMore_Discord {
            get {
                return ResourceManager.GetString("Settings.About.LearnMore.Discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string Settings_About_LearnMore_Documentation {
            get {
                return ResourceManager.GetString("Settings.About.LearnMore.Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub repository.
        /// </summary>
        public static string Settings_About_LearnMore_GitHub {
            get {
                return ResourceManager.GetString("Settings.About.LearnMore.GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support me.
        /// </summary>
        public static string Settings_About_LearnMore_Support {
            get {
                return ResourceManager.GetString("Settings.About.LearnMore.Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all files downloaded during the optimization process..
        /// </summary>
        public static string Settings_Advanced_ClearResources_Description {
            get {
                return ResourceManager.GetString("Settings.Advanced.ClearResources.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear resources.
        /// </summary>
        public static string Settings_Advanced_ClearResources_Title {
            get {
                return ResourceManager.GetString("Settings.Advanced.ClearResources.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all rollback data from optimizations..
        /// </summary>
        public static string Settings_Advanced_ClearRevertDatas_Description {
            get {
                return ResourceManager.GetString("Settings.Advanced.ClearRevertDatas.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all revert data.
        /// </summary>
        public static string Settings_Advanced_ClearRevertDatas_Title {
            get {
                return ResourceManager.GetString("Settings.Advanced.ClearRevertDatas.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Settings_Advanced_Header {
            get {
                return ResourceManager.GetString("Settings.Advanced.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the application&apos;s root directory, where all necessary files are stored..
        /// </summary>
        public static string Settings_Advanced_OpenRootDir_Description {
            get {
                return ResourceManager.GetString("Settings.Advanced.OpenRootDir.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open root directory.
        /// </summary>
        public static string Settings_Advanced_OpenRootDir_Title {
            get {
                return ResourceManager.GetString("Settings.Advanced.OpenRootDir.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Settings_Appearance_Header {
            get {
                return ResourceManager.GetString("Settings.Appearance.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your preferred language..
        /// </summary>
        public static string Settings_Appearance_LanguageSelector_Description {
            get {
                return ResourceManager.GetString("Settings.Appearance.LanguageSelector.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Appearance_LanguageSelector_Title {
            get {
                return ResourceManager.GetString("Settings.Appearance.LanguageSelector.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Settings_Appearance_ThemeSelector_Dark {
            get {
                return ResourceManager.GetString("Settings.Appearance.ThemeSelector.Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your preferred theme for the app..
        /// </summary>
        public static string Settings_Appearance_ThemeSelector_Description {
            get {
                return ResourceManager.GetString("Settings.Appearance.ThemeSelector.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Contrast.
        /// </summary>
        public static string Settings_Appearance_ThemeSelector_HighContrast {
            get {
                return ResourceManager.GetString("Settings.Appearance.ThemeSelector.HighContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Settings_Appearance_ThemeSelector_Light {
            get {
                return ResourceManager.GetString("Settings.Appearance.ThemeSelector.Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Settings_Appearance_ThemeSelector_Title {
            get {
                return ResourceManager.GetString("Settings.Appearance.ThemeSelector.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to delete all resources downloaded or generated during the optimization process. Please note that this action is permanent and cannot be undone, so make sure you are certain before proceeding..
        /// </summary>
        public static string Settings_ClearResources_Description {
            get {
                return ResourceManager.GetString("Settings.ClearResources.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to delete all rollback data generated after the optimization process. This means you will no longer be able to restore the pre-optimization state, so please think carefully before confirming..
        /// </summary>
        public static string Settings_ClearRevertData_Description {
            get {
                return ResourceManager.GetString("Settings.ClearRevertData.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Header_Title {
            get {
                return ResourceManager.GetString("Settings.Header.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to restart the application to apply the new language..
        /// </summary>
        public static string Settings_LanguageChanged_Description {
            get {
                return ResourceManager.GetString("Settings.LanguageChanged.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language change.
        /// </summary>
        public static string Settings_LanguageChanged_Title {
            get {
                return ResourceManager.GetString("Settings.LanguageChanged.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize.
        /// </summary>
        public static string Settings_Optimize_Header {
            get {
                return ResourceManager.GetString("Settings.Optimize.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout for each shell command execution (milliseconds)..
        /// </summary>
        public static string Settings_Optimize_ShellTimeout_Description {
            get {
                return ResourceManager.GetString("Settings.Optimize.ShellTimeout.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell service timeout.
        /// </summary>
        public static string Settings_Optimize_ShellTimeout_Title {
            get {
                return ResourceManager.GetString("Settings.Optimize.ShellTimeout.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do NOT change unless you know exactly what you are doing.
        /// </summary>
        public static string Settings_Optimize_ShellTimeout_Warning {
            get {
                return ResourceManager.GetString("Settings.Optimize.ShellTimeout.Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Sidebar_Dashboard {
            get {
                return ResourceManager.GetString("Sidebar.Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize.
        /// </summary>
        public static string Sidebar_Optimize {
            get {
                return ResourceManager.GetString("Sidebar.Optimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Sidebar_Settings {
            get {
                return ResourceManager.GetString("Sidebar.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while opening the folder or file. Please check the log..
        /// </summary>
        public static string Snackbar_OpenFailed_Message {
            get {
                return ResourceManager.GetString("Snackbar.OpenFailed.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open the folder or file.
        /// </summary>
        public static string Snackbar_OpenFailed_Title {
            get {
                return ResourceManager.GetString("Snackbar.OpenFailed.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while opening the path. Please check the log..
        /// </summary>
        public static string Snackbar_OpenLinkFailed_Message {
            get {
                return ResourceManager.GetString("Snackbar.OpenLinkFailed.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open the path.
        /// </summary>
        public static string Snackbar_OpenLinkFailed_Title {
            get {
                return ResourceManager.GetString("Snackbar.OpenLinkFailed.Title", resourceCulture);
            }
        }
    }
}
